/******************************************************************************
 * Copyright (C) 2010-2011 Lastrix                                            *
 * This file is part of ASN1S.                                                *
 *                                                                            *
 * ASN1S is free software: you can redistribute it and/or modify              *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation, either version 2 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * ASN1S is distributed in the hope that it will be useful,                   *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with ASN1S. If not, see <http://www.gnu.org/licenses/>.              *
 ******************************************************************************/

/* Generated By:JavaCC: Do not edit this line. ASN1SchemaCompilerTreeConstants.java Version 5.0 */
package org.lastrix.asn1s.schema.parser;

public interface ASN1SchemaCompilerTreeConstants {
	public int JJTPARSE                              = 0;

	public int JJTMODULEDEFINITION                   = 1;

	public int JJTEXTERNALVALUEREFERENCE             = 2;

	public int JJTSIGNEDNUMBER                       = 3;

	public int JJTMODULEIDENTIFIER                   = 4;

	public int JJTDEFINITEIDENTIFIER                 = 5;

	public int JJTOBJIDCOMPONENTSLIST                = 6;

	public int JJTOBJIDCOMPONENT                     = 7;

	public int JJTNUMBERFORM                         = 8;

	public int JJTNUMBER                             = 9;

	public int JJTNAMEANDNUMBERFORM                  = 10;

	public int JJTTAGDEFAULT                         = 11;

	public int JJTEXTENSIONDEFAULT                   = 12;

	public int JJTMODULEBODY                         = 13;

	public int JJTEXPORTS                            = 14;

	public int JJTSYMBOLSEXPORTED                    = 15;

	public int JJTIMPORTS                            = 16;

	public int JJTSYMBOLSIMPORTED                    = 17;

	public int JJTSYMBOLSFROMMODULELIST              = 18;

	public int JJTSYMBOLSFROMMODULE                  = 19;

	public int JJTGLOBALMODULEREFERENCE              = 20;

	public int JJTASSIGNEDIDENTIFIER                 = 21;

	public int JJTSYMBOLLIST                         = 22;

	public int JJTSYMBOL                             = 23;

	public int JJTREFERENCE                          = 24;

	public int JJTASSIGNMENTLIST                     = 25;

	public int JJTVOID                               = 26;

	public int JJTDEFINEDTYPE                        = 27;

	public int JJTEXTERNALTYPEREFERENCE              = 28;

	public int JJTABSOLUTEREFERENCE                  = 29;

	public int JJTITEMSPEC                           = 30;

	public int JJTCOMPONENTID                        = 31;

	public int JJTTYPEASSIGNMENT                     = 32;

	public int JJTVALUEASSIGNMENT                    = 33;

	public int JJTVALUESETTYPEASSIGNMENT             = 34;

	public int JJTVALUESET                           = 35;

	public int JJTTYPE                               = 36;

	public int JJTBUILTINTYPE                        = 37;

	public int JJTNAMEDTYPE                          = 38;

	public int JJTREFERENCEDTYPE                     = 39;

	public int JJTBOOLEANTYPE                        = 40;

	public int JJTINTEGERTYPE                        = 41;

	public int JJTNAMEDNUMBERLIST                    = 42;

	public int JJTNAMEDNUMBER                        = 43;

	public int JJTENUMERATEDTYPE                     = 44;

	public int JJTENUMERATIONS                       = 45;

	public int JJTENUMERATION                        = 46;

	public int JJTENUMERATIONITEM                    = 47;

	public int JJTREALTYPE                           = 48;

	public int JJTBITSTRINGTYPE                      = 49;

	public int JJTNAMEDBITLIST                       = 50;

	public int JJTNAMEDBIT                           = 51;

	public int JJTOCTETSTRINGTYPE                    = 52;

	public int JJTNULLTYPE                           = 53;

	public int JJTSEQUENCETYPE                       = 54;

	public int JJTEXTENSIONANDEXCEPTION              = 55;

	public int JJTOPTIONALEXTENSIONMARKER            = 56;

	public int JJTCOMPONENTTYPELISTS                 = 57;

	public int JJTEXTENSIONENDMARKER                 = 58;

	public int JJTEXTENSIONADDITIONS                 = 59;

	public int JJTEXTENSIONADDITIONSLIST             = 60;

	public int JJTEXTENSIONADDITION                  = 61;

	public int JJTEXTENSIONADDITIONGROUP             = 62;

	public int JJTVERSIONNUMBER                      = 63;

	public int JJTCOMPONENTTYPELIST                  = 64;

	public int JJTCOMPONENTTYPE                      = 65;

	public int JJTSEQUENCEOFTYPE                     = 66;

	public int JJTSETTYPE                            = 67;

	public int JJTSETOFTYPE                          = 68;

	public int JJTCHOICETYPE                         = 69;

	public int JJTALTERNATIVETYPELISTS               = 70;

	public int JJTEXTENSIONADDITIONALTERNATIVES      = 71;

	public int JJTEXTENSIONADDITIONALTERNATIVESLIST  = 72;

	public int JJTEXTENSIONADDITIONALTERNATIVE       = 73;

	public int JJTEXTENSIONADDITIONALTERNATIVESGROUP = 74;

	public int JJTALTERNATIVETYPELIST                = 75;

	public int JJTSELECTIONTYPE                      = 76;

	public int JJTTAGGEDTYPE                         = 77;

	public int JJTTAGGINGMETHOD                      = 78;

	public int JJTTAG                                = 79;

	public int JJTCLASSNUMBER                        = 80;

	public int JJTCLASS                              = 81;

	public int JJTEMBEDDEDPDVTYPE                    = 82;

	public int JJTEXTERNALTYPE                       = 83;

	public int JJTCHARACTERSTRINGTYPE                = 84;

	public int JJTRESTRICTEDCHARACTERSTRINGTYPE      = 85;

	public int JJTUNRESTRICTEDCHARACTERSTRINGTYPE    = 86;

	public int JJTCHARACTERSTRINGVALUE               = 87;

	public int JJTUNRESTRICTEDCHARACTERSTRINGVALUE   = 88;

	public int JJTUSEFULTYPE                         = 89;

	public int JJTTYPEWITHCONSTRAINT                 = 90;

	public int JJTCONSTRAINT                         = 91;

	public int JJTCONSTRAINTSPEC                     = 92;

	public int JJTGENERALCONSTRAINT                  = 93;

	public int JJTUSERDEFINEDCONSTRAINT              = 94;

	public int JJTUSERDEFINEDCONSTRAINTPARAMETER     = 95;

	public int JJTCONTENTSCONSTRAINT                 = 96;

	public int JJTEXCEPTIONSPEC                      = 97;

	public int JJTEXCEPTIONIDENTIFICATION            = 98;

	public int JJTSUBTYPECONSTRAINT                  = 99;

	public int JJTELEMENTSETSPECS                    = 100;

	public int JJTADDITIONALELEMENTSETSPEC           = 101;

	public int JJTELEMENTSETSPEC                     = 102;

	public int JJTUNIONS                             = 103;

	public int JJTINTERSECTIONS                      = 104;

	public int JJTINTERSECTIONELEMENTS               = 105;

	public int JJTEXCLUSIONS                         = 106;

	public int JJTUNIONMARK                          = 107;

	public int JJTINTERSECTIONMARK                   = 108;

	public int JJTELEMENTS                           = 109;

	public int JJTSUBTYPEELEMENTS                    = 110;

	public int JJTCONTAINEDSUBTYPE                   = 111;

	public int JJTVALUERANGE                         = 112;

	public int JJTLOWERENDPOINT                      = 113;

	public int JJTUPPERENDPOINT                      = 114;

	public int JJTLOWERENDVALUE                      = 115;

	public int JJTUPPERENDVALUE                      = 116;

	public int JJTSIZECONSTRAINT                     = 117;

	public int JJTPERMITTEDALPHABET                  = 118;

	public int JJTTYPECONSTRAINT                     = 119;

	public int JJTINNERTYPECONSTRAINTS               = 120;

	public int JJTSINGLETYPECONSTRAINT               = 121;

	public int JJTMULTIPLETYPECONSTRAINT             = 122;

	public int JJTFULLSPECIFICATION                  = 123;

	public int JJTPARTIALSPECIFICATION               = 124;

	public int JJTTYPECONSTRAINTS                    = 125;

	public int JJTNAMEDCONSTRAINT                    = 126;

	public int JJTCOMPONENTCONSTRAINT                = 127;

	public int JJTVALUECONSTRAINT                    = 128;

	public int JJTPARAMETRIZEDASSIGNMENT             = 129;

	public int JJTPARAMETRIZEDTYPEASSIGNMENT         = 130;

	public int JJTPARAMETRIZEDVALUEASSIGNMENT        = 131;

	public int JJTPARAMETRIZEDVALUESETTYPEASSIGNMENT = 132;

	public int JJTPARAMETERLIST                      = 133;

	public int JJTPARAMETER                          = 134;

	public int JJTPARAMGOVERNOR                      = 135;

	public int JJTGOVERNOR                           = 136;

	public int JJTDUMMYGOVERNOR                      = 137;

	public int JJTDUMMYREFERENCE                     = 138;

	public int JJTPARAMETRIZEDTYPE                   = 139;

	public int JJTSIMPLEDEFINEDTYPE                  = 140;

	public int JJTPARAMETRIZEDVALUESETTYPE           = 141;

	public int JJTACTUALPARAMETERLIST                = 142;

	public int JJTACTUALPARAMETER                    = 143;

	public int JJTPRESENCECONSTRAINT                 = 144;

	public int JJTPATTERNCONSTRAINT                  = 145;

	public int JJTTYPEREFERENCE                      = 146;

	public int JJTIDENTIFIER                         = 147;

	public int JJTVALUEREFERENCE                     = 148;

	public int JJTMODULEREFERENCE                    = 149;

	public int JJTOBJECTCLASSREFERENCE               = 150;

	public int JJTOBJECTREFERENCE                    = 151;

	public int JJTTYPEFIELDREFERENCE                 = 152;

	public int JJTVALUEFIELDREFERENCE                = 153;

	public int JJTVALUESETFIELDREFERENCE             = 154;

	public int JJTOBJECTFIELDREFERENCE               = 155;

	public int JJTVALUE                              = 156;

	public int JJTDEFINEDVALUE                       = 157;

	public int JJTOBJECTIDENTIFIERTYPE               = 158;

	public int JJTOBJECTIDENTIFIERVALUE              = 159;

	public int JJTRELATIVEOIDTYPE                    = 160;

	public int JJTRELATIVEOIDVALUE                   = 161;

	public int JJTRELATIVEOIDCOMPONENTSLIST          = 162;

	public int JJTRELATIVEOIDCOMPONENTS              = 163;

	public int JJTBUILTINVALUE                       = 164;

	public int JJTREFERENCEDVALUE                    = 165;

	public int JJTNAMEDVALUE                         = 166;

	public int JJTBOOLEANVALUE                       = 167;

	public int JJTENUMERATEDVALUE                    = 168;

	public int JJTINTEGERVALUE                       = 169;

	public int JJTREALVALUE                          = 170;

	public int JJTNUMERICREALVALUE                   = 171;

	public int JJTSPECIALREALVALUE                   = 172;

	public int JJTBITSTRINGVALUE                     = 173;

	public int JJTCHOICEVALUE                        = 174;

	public int JJTEXTERNALVALUE                      = 175;

	public int JJTSETOFVALUE                         = 176;

	public int JJTSETVALUE                           = 177;

	public int JJTSEQUENCEOFVALUE                    = 178;

	public int JJTVALUELIST                          = 179;

	public int JJTNAMEDVALUELIST                     = 180;

	public int JJTSEQUENCEVALUE                      = 181;

	public int JJTCOMPONENTVALUELIST                 = 182;

	public int JJTOCTETSTRINGVALUE                   = 183;

	public int JJTNULLVALUE                          = 184;

	public int JJTIDENTIFIERLIST                     = 185;

	public int JJTPARAMETRIZEDVALUE                  = 186;

	public int JJTSIMPLEDEFINEDVALUE                 = 187;

	public int JJTRESTRICTEDCHARACTERSTRINGVALUE     = 188;

	public int JJTCHARACTERSTRINGLIST                = 189;

	public int JJTCHARSYMS                           = 190;

	public int JJTCHARSDEFN                          = 191;

	public int JJTQUADRUPLE                          = 192;

	public int JJTGROUP                              = 193;

	public int JJTPLANE                              = 194;

	public int JJTROW                                = 195;

	public int JJTCELL                               = 196;

	public int JJTTUPLE                              = 197;

	public int JJTTABLECOLUMN                        = 198;

	public int JJTTABLEROW                           = 199;

	public int JJTEMBEDDEDPDVVALUE                   = 200;


	public String[] jjtNodeName = {
	                              "Parse",
	                              "ModuleDefinition",
	                              "ExternalValueReference",
	                              "SignedNumber",
	                              "ModuleIdentifier",
	                              "DefiniteIdentifier",
	                              "ObjIdComponentsList",
	                              "ObjIdComponent",
	                              "NumberForm",
	                              "Number",
	                              "NameAndNumberForm",
	                              "TagDefault",
	                              "ExtensionDefault",
	                              "ModuleBody",
	                              "Exports",
	                              "SymbolsExported",
	                              "Imports",
	                              "SymbolsImported",
	                              "SymbolsFromModuleList",
	                              "SymbolsFromModule",
	                              "GlobalModuleReference",
	                              "AssignedIdentifier",
	                              "SymbolList",
	                              "Symbol",
	                              "Reference",
	                              "AssignmentList",
	                              "void",
	                              "DefinedType",
	                              "ExternalTypeReference",
	                              "AbsoluteReference",
	                              "ItemSpec",
	                              "ComponentId",
	                              "TypeAssignment",
	                              "ValueAssignment",
	                              "ValueSetTypeAssignment",
	                              "ValueSet",
	                              "Type",
	                              "BuiltinType",
	                              "NamedType",
	                              "ReferencedType",
	                              "BooleanType",
	                              "IntegerType",
	                              "NamedNumberList",
	                              "NamedNumber",
	                              "EnumeratedType",
	                              "Enumerations",
	                              "Enumeration",
	                              "EnumerationItem",
	                              "RealType",
	                              "BitStringType",
	                              "NamedBitList",
	                              "NamedBit",
	                              "OctetStringType",
	                              "NullType",
	                              "SequenceType",
	                              "ExtensionAndException",
	                              "OptionalExtensionMarker",
	                              "ComponentTypeLists",
	                              "ExtensionEndMarker",
	                              "ExtensionAdditions",
	                              "ExtensionAdditionsList",
	                              "ExtensionAddition",
	                              "ExtensionAdditionGroup",
	                              "VersionNumber",
	                              "ComponentTypeList",
	                              "ComponentType",
	                              "SequenceOfType",
	                              "SetType",
	                              "SetOfType",
	                              "ChoiceType",
	                              "AlternativeTypeLists",
	                              "ExtensionAdditionAlternatives",
	                              "ExtensionAdditionAlternativesList",
	                              "ExtensionAdditionAlternative",
	                              "ExtensionAdditionAlternativesGroup",
	                              "AlternativeTypeList",
	                              "SelectionType",
	                              "TaggedType",
	                              "TaggingMethod",
	                              "Tag",
	                              "ClassNumber",
	                              "Class",
	                              "EmbeddedPDVType",
	                              "ExternalType",
	                              "CharacterStringType",
	                              "RestrictedCharacterStringType",
	                              "UnrestrictedCharacterStringType",
	                              "CharacterStringValue",
	                              "UnrestrictedCharacterStringValue",
	                              "UsefulType",
	                              "TypeWithConstraint",
	                              "Constraint",
	                              "ConstraintSpec",
	                              "GeneralConstraint",
	                              "UserDefinedConstraint",
	                              "UserDefinedConstraintParameter",
	                              "ContentsConstraint",
	                              "ExceptionSpec",
	                              "ExceptionIdentification",
	                              "SubtypeConstraint",
	                              "ElementSetSpecs",
	                              "AdditionalElementSetSpec",
	                              "ElementSetSpec",
	                              "Unions",
	                              "Intersections",
	                              "IntersectionElements",
	                              "Exclusions",
	                              "UnionMark",
	                              "IntersectionMark",
	                              "Elements",
	                              "SubtypeElements",
	                              "ContainedSubtype",
	                              "ValueRange",
	                              "LowerEndpoint",
	                              "UpperEndpoint",
	                              "LowerEndValue",
	                              "UpperEndValue",
	                              "SizeConstraint",
	                              "PermittedAlphabet",
	                              "TypeConstraint",
	                              "InnerTypeConstraints",
	                              "SingleTypeConstraint",
	                              "MultipleTypeConstraint",
	                              "FullSpecification",
	                              "PartialSpecification",
	                              "TypeConstraints",
	                              "NamedConstraint",
	                              "ComponentConstraint",
	                              "ValueConstraint",
	                              "ParametrizedAssignment",
	                              "ParametrizedTypeAssignment",
	                              "ParametrizedValueAssignment",
	                              "ParametrizedValueSetTypeAssignment",
	                              "ParameterList",
	                              "Parameter",
	                              "ParamGovernor",
	                              "Governor",
	                              "DummyGovernor",
	                              "DummyReference",
	                              "ParametrizedType",
	                              "SimpleDefinedType",
	                              "ParametrizedValueSetType",
	                              "ActualParameterList",
	                              "ActualParameter",
	                              "PresenceConstraint",
	                              "PatternConstraint",
	                              "TypeReference",
	                              "identifier",
	                              "ValueReference",
	                              "ModuleReference",
	                              "ObjectClassReference",
	                              "ObjectReference",
	                              "TypeFieldReference",
	                              "ValueFieldReference",
	                              "ValueSetFieldReference",
	                              "ObjectFieldReference",
	                              "Value",
	                              "DefinedValue",
	                              "ObjectIdentifierType",
	                              "ObjectIdentifierValue",
	                              "RelativeOIDType",
	                              "RelativeOIDValue",
	                              "RelativeOIDComponentsList",
	                              "RelativeOIDComponents",
	                              "BuiltinValue",
	                              "ReferencedValue",
	                              "NamedValue",
	                              "BooleanValue",
	                              "EnumeratedValue",
	                              "IntegerValue",
	                              "RealValue",
	                              "NumericRealValue",
	                              "SpecialRealValue",
	                              "BitStringValue",
	                              "ChoiceValue",
	                              "ExternalValue",
	                              "SetOfValue",
	                              "SetValue",
	                              "SequenceOfValue",
	                              "ValueList",
	                              "NamedValueList",
	                              "SequenceValue",
	                              "ComponentValueList",
	                              "OctetStringValue",
	                              "NullValue",
	                              "IdentifierList",
	                              "ParametrizedValue",
	                              "SimpleDefinedValue",
	                              "RestrictedCharacterStringValue",
	                              "CharacterStringList",
	                              "CharSyms",
	                              "CharsDefn",
	                              "Quadruple",
	                              "Group",
	                              "Plane",
	                              "Row",
	                              "Cell",
	                              "Tuple",
	                              "TableColumn",
	                              "TableRow",
	                              "EmbeddedPDVValue",
	};
}
/* JavaCC - OriginalChecksum=48d0b4a4eb406f65df154f63f6f4e93b (do not edit this line) */
