/******************************************************************************
 * Copyright (C) 2010-2011 Lastrix                                            *
 * This file is part of ASN1S.                                                *
 *                                                                            *
 * ASN1S is free software: you can redistribute it and/or modify              *
 * it under the terms of the GNU General Public License as published by       *
 * the Free Software Foundation, either version 2 of the License, or          *
 * (at your option) any later version.                                        *
 *                                                                            *
 * ASN1S is distributed in the hope that it will be useful,                   *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with ASN1S. If not, see <http://www.gnu.org/licenses/>.              *
 ******************************************************************************/

/* Generated By:JavaCC: Do not edit this line. ASN1SchemaCompilerVisitor.java Version 5.0 */
package org.lastrix.asn1s.schema.parser;

public interface ASN1SchemaCompilerVisitor {
	public Object visit(SimpleNode node, Object data);

	public Object visit(ASTParse node, Object data);

	public Object visit(ASTModuleDefinition node, Object data);

	public Object visit(ASTExternalValueReference node, Object data);

	public Object visit(ASTSignedNumber node, Object data);

	public Object visit(ASTModuleIdentifier node, Object data);

	public Object visit(ASTDefiniteIdentifier node, Object data);

	public Object visit(ASTObjIdComponentsList node, Object data);

	public Object visit(ASTObjIdComponent node, Object data);

	public Object visit(ASTNumberForm node, Object data);

	public Object visit(ASTNumber node, Object data);

	public Object visit(ASTNameAndNumberForm node, Object data);

	public Object visit(ASTTagDefault node, Object data);

	public Object visit(ASTExtensionDefault node, Object data);

	public Object visit(ASTModuleBody node, Object data);

	public Object visit(ASTExports node, Object data);

	public Object visit(ASTSymbolsExported node, Object data);

	public Object visit(ASTImports node, Object data);

	public Object visit(ASTSymbolsImported node, Object data);

	public Object visit(ASTSymbolsFromModuleList node, Object data);

	public Object visit(ASTSymbolsFromModule node, Object data);

	public Object visit(ASTGlobalModuleReference node, Object data);

	public Object visit(ASTAssignedIdentifier node, Object data);

	public Object visit(ASTSymbolList node, Object data);

	public Object visit(ASTSymbol node, Object data);

	public Object visit(ASTReference node, Object data);

	public Object visit(ASTAssignmentList node, Object data);

	public Object visit(ASTDefinedType node, Object data);

	public Object visit(ASTExternalTypeReference node, Object data);

	public Object visit(ASTAbsoluteReference node, Object data);

	public Object visit(ASTItemSpec node, Object data);

	public Object visit(ASTComponentId node, Object data);

	public Object visit(ASTTypeAssignment node, Object data);

	public Object visit(ASTValueAssignment node, Object data);

	public Object visit(ASTValueSetTypeAssignment node, Object data);

	public Object visit(ASTValueSet node, Object data);

	public Object visit(ASTType node, Object data);

	public Object visit(ASTBuiltinType node, Object data);

	public Object visit(ASTNamedType node, Object data);

	public Object visit(ASTReferencedType node, Object data);

	public Object visit(ASTBooleanType node, Object data);

	public Object visit(ASTIntegerType node, Object data);

	public Object visit(ASTNamedNumberList node, Object data);

	public Object visit(ASTNamedNumber node, Object data);

	public Object visit(ASTEnumeratedType node, Object data);

	public Object visit(ASTEnumerations node, Object data);

	public Object visit(ASTEnumeration node, Object data);

	public Object visit(ASTEnumerationItem node, Object data);

	public Object visit(ASTRealType node, Object data);

	public Object visit(ASTBitStringType node, Object data);

	public Object visit(ASTNamedBitList node, Object data);

	public Object visit(ASTNamedBit node, Object data);

	public Object visit(ASTOctetStringType node, Object data);

	public Object visit(ASTNullType node, Object data);

	public Object visit(ASTSequenceType node, Object data);

	public Object visit(ASTExtensionAndException node, Object data);

	public Object visit(ASTOptionalExtensionMarker node, Object data);

	public Object visit(ASTComponentTypeLists node, Object data);

	public Object visit(ASTExtensionEndMarker node, Object data);

	public Object visit(ASTExtensionAdditions node, Object data);

	public Object visit(ASTExtensionAdditionsList node, Object data);

	public Object visit(ASTExtensionAddition node, Object data);

	public Object visit(ASTExtensionAdditionGroup node, Object data);

	public Object visit(ASTVersionNumber node, Object data);

	public Object visit(ASTComponentTypeList node, Object data);

	public Object visit(ASTComponentType node, Object data);

	public Object visit(ASTSequenceOfType node, Object data);

	public Object visit(ASTSetType node, Object data);

	public Object visit(ASTSetOfType node, Object data);

	public Object visit(ASTChoiceType node, Object data);

	public Object visit(ASTAlternativeTypeLists node, Object data);

	public Object visit(ASTExtensionAdditionAlternatives node, Object data);

	public Object visit(ASTExtensionAdditionAlternativesList node, Object data);

	public Object visit(ASTExtensionAdditionAlternative node, Object data);

	public Object visit(ASTExtensionAdditionAlternativesGroup node, Object data);

	public Object visit(ASTAlternativeTypeList node, Object data);

	public Object visit(ASTSelectionType node, Object data);

	public Object visit(ASTTaggedType node, Object data);

	public Object visit(ASTTaggingMethod node, Object data);

	public Object visit(ASTTag node, Object data);

	public Object visit(ASTClassNumber node, Object data);

	public Object visit(ASTClass node, Object data);

	public Object visit(ASTEmbeddedPDVType node, Object data);

	public Object visit(ASTExternalType node, Object data);

	public Object visit(ASTCharacterStringType node, Object data);

	public Object visit(ASTRestrictedCharacterStringType node, Object data);

	public Object visit(ASTUnrestrictedCharacterStringType node, Object data);

	public Object visit(ASTCharacterStringValue node, Object data);

	public Object visit(ASTUnrestrictedCharacterStringValue node, Object data);

	public Object visit(ASTUsefulType node, Object data);

	public Object visit(ASTTypeWithConstraint node, Object data);

	public Object visit(ASTConstraint node, Object data);

	public Object visit(ASTConstraintSpec node, Object data);

	public Object visit(ASTGeneralConstraint node, Object data);

	public Object visit(ASTUserDefinedConstraint node, Object data);

	public Object visit(ASTUserDefinedConstraintParameter node, Object data);

	public Object visit(ASTContentsConstraint node, Object data);

	public Object visit(ASTExceptionSpec node, Object data);

	public Object visit(ASTExceptionIdentification node, Object data);

	public Object visit(ASTSubtypeConstraint node, Object data);

	public Object visit(ASTElementSetSpecs node, Object data);

	public Object visit(ASTAdditionalElementSetSpec node, Object data);

	public Object visit(ASTElementSetSpec node, Object data);

	public Object visit(ASTUnions node, Object data);

	public Object visit(ASTIntersections node, Object data);

	public Object visit(ASTIntersectionElements node, Object data);

	public Object visit(ASTExclusions node, Object data);

	public Object visit(ASTUnionMark node, Object data);

	public Object visit(ASTIntersectionMark node, Object data);

	public Object visit(ASTElements node, Object data);

	public Object visit(ASTSubtypeElements node, Object data);

	public Object visit(ASTContainedSubtype node, Object data);

	public Object visit(ASTValueRange node, Object data);

	public Object visit(ASTLowerEndpoint node, Object data);

	public Object visit(ASTUpperEndpoint node, Object data);

	public Object visit(ASTLowerEndValue node, Object data);

	public Object visit(ASTUpperEndValue node, Object data);

	public Object visit(ASTSizeConstraint node, Object data);

	public Object visit(ASTPermittedAlphabet node, Object data);

	public Object visit(ASTTypeConstraint node, Object data);

	public Object visit(ASTInnerTypeConstraints node, Object data);

	public Object visit(ASTSingleTypeConstraint node, Object data);

	public Object visit(ASTMultipleTypeConstraint node, Object data);

	public Object visit(ASTFullSpecification node, Object data);

	public Object visit(ASTPartialSpecification node, Object data);

	public Object visit(ASTTypeConstraints node, Object data);

	public Object visit(ASTNamedConstraint node, Object data);

	public Object visit(ASTComponentConstraint node, Object data);

	public Object visit(ASTValueConstraint node, Object data);

	public Object visit(ASTParametrizedAssignment node, Object data);

	public Object visit(ASTParametrizedTypeAssignment node, Object data);

	public Object visit(ASTParametrizedValueAssignment node, Object data);

	public Object visit(ASTParametrizedValueSetTypeAssignment node, Object data);

	public Object visit(ASTParameterList node, Object data);

	public Object visit(ASTParameter node, Object data);

	public Object visit(ASTParamGovernor node, Object data);

	public Object visit(ASTGovernor node, Object data);

	public Object visit(ASTDummyGovernor node, Object data);

	public Object visit(ASTDummyReference node, Object data);

	public Object visit(ASTParametrizedType node, Object data);

	public Object visit(ASTSimpleDefinedType node, Object data);

	public Object visit(ASTParametrizedValueSetType node, Object data);

	public Object visit(ASTActualParameterList node, Object data);

	public Object visit(ASTActualParameter node, Object data);

	public Object visit(ASTPresenceConstraint node, Object data);

	public Object visit(ASTPatternConstraint node, Object data);

	public Object visit(ASTTypeReference node, Object data);

	public Object visit(ASTidentifier node, Object data);

	public Object visit(ASTValueReference node, Object data);

	public Object visit(ASTModuleReference node, Object data);

	public Object visit(ASTObjectClassReference node, Object data);

	public Object visit(ASTObjectReference node, Object data);

	public Object visit(ASTTypeFieldReference node, Object data);

	public Object visit(ASTValueFieldReference node, Object data);

	public Object visit(ASTValueSetFieldReference node, Object data);

	public Object visit(ASTObjectFieldReference node, Object data);

	public Object visit(ASTValue node, Object data);

	public Object visit(ASTDefinedValue node, Object data);

	public Object visit(ASTObjectIdentifierType node, Object data);

	public Object visit(ASTObjectIdentifierValue node, Object data);

	public Object visit(ASTRelativeOIDType node, Object data);

	public Object visit(ASTRelativeOIDValue node, Object data);

	public Object visit(ASTRelativeOIDComponentsList node, Object data);

	public Object visit(ASTRelativeOIDComponents node, Object data);

	public Object visit(ASTBuiltinValue node, Object data);

	public Object visit(ASTReferencedValue node, Object data);

	public Object visit(ASTNamedValue node, Object data);

	public Object visit(ASTBooleanValue node, Object data);

	public Object visit(ASTEnumeratedValue node, Object data);

	public Object visit(ASTIntegerValue node, Object data);

	public Object visit(ASTRealValue node, Object data);

	public Object visit(ASTNumericRealValue node, Object data);

	public Object visit(ASTSpecialRealValue node, Object data);

	public Object visit(ASTBitStringValue node, Object data);

	public Object visit(ASTChoiceValue node, Object data);

	public Object visit(ASTExternalValue node, Object data);

	public Object visit(ASTSetOfValue node, Object data);

	public Object visit(ASTSetValue node, Object data);

	public Object visit(ASTSequenceOfValue node, Object data);

	public Object visit(ASTValueList node, Object data);

	public Object visit(ASTNamedValueList node, Object data);

	public Object visit(ASTSequenceValue node, Object data);

	public Object visit(ASTComponentValueList node, Object data);

	public Object visit(ASTOctetStringValue node, Object data);

	public Object visit(ASTNullValue node, Object data);

	public Object visit(ASTIdentifierList node, Object data);

	public Object visit(ASTParametrizedValue node, Object data);

	public Object visit(ASTSimpleDefinedValue node, Object data);

	public Object visit(ASTRestrictedCharacterStringValue node, Object data);

	public Object visit(ASTCharacterStringList node, Object data);

	public Object visit(ASTCharSyms node, Object data);

	public Object visit(ASTCharsDefn node, Object data);

	public Object visit(ASTQuadruple node, Object data);

	public Object visit(ASTGroup node, Object data);

	public Object visit(ASTPlane node, Object data);

	public Object visit(ASTRow node, Object data);

	public Object visit(ASTCell node, Object data);

	public Object visit(ASTTuple node, Object data);

	public Object visit(ASTTableColumn node, Object data);

	public Object visit(ASTTableRow node, Object data);

	public Object visit(ASTEmbeddedPDVValue node, Object data);
}
/* JavaCC - OriginalChecksum=960c077464aea2f3750d7a59d4fe8cb9 (do not edit this line) */
